FROM python:latest
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
WORKDIR /dockerDjangoSetup
COPY requirements.txt /dockerDjangoSetup/
RUN pip install -r requirements.txt
COPY . /dockerDjangoSetup/