# Generated by Django 5.1.4 on 2025-01-11 13:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('iconUrl', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=400)),
                ('description', models.TextField()),
                ('video_name', models.TextField()),
                ('code', models.URLField(max_length=400)),
                ('preview', models.URLField(max_length=400)),
                ('skills', models.ManyToManyField(related_name='projects', to='skillsProjects.skill')),
            ],
        ),
    ]
