# Generated by Django 5.1.4 on 2024-12-22 10:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillsProjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('src', models.FileField(blank=True, null=True, upload_to='projects/videos/')),
                ('code', models.URLField(max_length=400)),
                ('preview', models.URLField(max_length=400)),
            ],
        ),
    ]
