# Generated by Django 5.1.4 on 2024-12-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillsProjects', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(related_name='projects', to='skillsProjects.skill'),
        ),
    ]
